apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  annotations: 
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: "0c1e5d15-3440-4b0f-973c-f95b54377c63"

spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saiyam911/kubeconeu:sha-567d8f7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  type: ClusterIP
  selector:
    app: helloservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

